//___FILEHEADER___

___IMPORTHEADER_cocoaTouchSubclass___

NS_ASSUME_NONNULL_BEGIN

extern NSString *const k___FILEBASENAMEASIDENTIFIER___Identifier;
@interface ___FILEBASENAMEASIDENTIFIER___ : ___VARIABLE_cocoaTouchSubclass___

@end

NS_ASSUME_NONNULL_END
