//___FILEHEADER___

___IMPORTHEADER_cocoaTouchSubclass___

extern NSString *const k___FILEBASENAMEASIDENTIFIER___Identifier;
@interface ___FILEBASENAMEASIDENTIFIER___ : ___VARIABLE_cocoaTouchSubclass___

@end
